name: getx_mvc_cli_pattern
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_form_builder: ^7.1.0
  image_picker: ^0.8.4+9
  permission_handler: ^9.0.1
  form_builder_validators: ^7.4.0
  pin_code_text_field: ^1.8.0
  pin_code_fields: ^7.3.0
  signalr_core: ^1.1.1
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.13
  sizer: ^2.0.15
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  extended_image: ^6.2.1
  dio: ^4.0.4
  font_awesome_flutter: ^9.2.0
  shimmer: ^2.0.0
  flutter_rating_bar: ^4.0.0
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  path_provider: any
  auto_size_text: ^3.0.0
  country_code_picker: ^2.0.2
  package_info_plus: ^1.4.2
  device_info_plus: ^8.0.0
  modal_bottom_sheet: ^2.0.1
  flutter_staggered_grid_view: ^0.6.1
  timeago: ^3.2.2
  extended_sliver: ^2.1.3
  intl_phone_number_input: ^0.7.0+2
  intl_phone_field: ^3.1.0
  jwt_decoder: ^2.0.1
  url_launcher: ^6.1.2
  file_picker: any
  image_cropper: ^2.0.3
  http: ^0.13.4
  flutter_native_splash: ^2.2.5
  qr_flutter: ^4.0.0
  fl_chart: ^0.55.2
  emoji_picker_flutter: ^1.5.1
  google_maps_flutter: ^2.2.1
  location: ^4.4.0
  dropdown_button2: ^1.9.2
  percent_indicator: ^4.2.2
  control_style: ^0.0.3
  chat_bubbles: ^1.3.1
  language_picker: ^0.4.2
  country_pickers: ^2.0.0
  flutter_progress_hud: ^2.0.2
  flutter_spinkit: ^5.1.0
  firebase_core: ^2.4.1
  firebase_dynamic_links: ^5.0.11
  qr_code_scanner: ^1.0.1
  geolocator: ^9.0.2
  lottie: ^1.4.1
  animate_do: ^3.0.2
  google_places_flutter: ^2.0.5
  sentry_flutter: ^6.19.0
  dio_log: ^2.0.4
  easy_debounce: ^2.0.3
  google_maps_cluster_manager: any
  custom_searchable_dropdown: ^2.1.1
  firebase_messaging: ^14.2.5
  flutter_local_notifications: ^13.0.0
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

